boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('', views.home, name='home'),
    path('boards/<int:board_id>/', views.board_topics, name='board_topics'),
    path('boards/<int:board_id>/new/', views.new_topic, name='new_topic'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('boards.urls')),
]

boards/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Topic(models.Model):
    subject = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='topics')
    starter = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='topics')

    def __str__(self):
        return self.subject


class Post(models.Model):
    message = models.TextField()
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='posts')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='+')

    def __str__(self):
        return '{0} by {1}'.format(self.message[:20] + ' by ' + str(self.created_by))

boards/forms.py
from django import forms
from .models import Topic


class NewTopicForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea(
        attrs={'rows': 5, 'placeholder': 'What is on your mind?'}
    ),
        max_length=4000,
        help_text='The max length of the text is 4000.')

    class Meta:
        model = Topic
        fields = ['subject', 'message']

boards/views.py
from django.http import Http404
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from .models import Board, Topic, Post
from .forms import NewTopicForm


# Create your views here.
def home(request):
    boards = Board.objects.all()
    return render(request, 'boards/home.html', {'boards': boards})


def board_topics(request, board_id):
    try:
        board = Board.objects.get(id=board_id)
    except Board.DoesNotExist:
        raise Http404('Board not found !!!')

    return render(request, 'boards/topics.html', {'board': board})


def new_topic(request, board_id):
    board = get_object_or_404(Board, id=board_id)
    user = User.objects.first()  # TODO: get the currently logged in user

    if request.method == 'POST':
        form = NewTopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.board = board
            topic.starter = user
            topic.save()
            post = Post.objects.create(
                message=form.cleaned_data.get('message'),
                topic=topic,
                created_by=user
            )
            return redirect('boards:board_topics', board_id)  # TODO: redirect to the created topic page
    else:
        form = NewTopicForm()

    return render(request, 'boards/new_topic.html', {'board': board, 'form': form})

boards/templates/boards/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'boards/styles.css' %}" type="text/css">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'boards:home' %}">Django Boards</a>
    </div>
</nav>
<div class="container">
    <ol class="breadcrumb my-4">
        {% block breadcrumb %}
        {% endblock %}
    </ol>
    {% block content %}
    {% endblock %}
</div>
<script src="http://code.jquery.com/jquery-3.3.1.js"
        integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

boards/templates/boards/home.html
{% extends 'boards/base.html' %}

{% block title %}
Home Page
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Boards</li>
{% endblock %}

{% block content %}
<!--<h1>Boards</h1>-->
<!--<table border="1">-->
<!--<thead>-->
<!--<tr>-->
<!--<th>Board</th>-->
<!--<th>Posts</th>-->
<!--<th>Topics</th>-->
<!--<th>Last Post</th>-->
<!--</tr>-->
<!--</thead>-->
<!--<tbody>-->
<!--{% for board in boards %}-->
<!--<tr>-->
<!--<td>-->
<!--{{ board.name }}<br>-->
<!--<small style="color: #888">{{ board.description }}</small>-->
<!--</td>-->
<!--<td>{{ board.topics.posts.count }}</td>-->
<!--<td>{{ board.topics.count }}</td>-->
<!--<td></td>-->
<!--</tr>-->
<!--{% endfor %}-->
<!--</tbody>-->
<!--</table>-->

<table class="table">
    <!--"thead-inverse" replaced by "thead-dark" class in Bootstrap 4.0 as below-->
    <thead class="thead-dark">
    <tr>
        <th>Board</th>
        <th>Posts</th>
        <th>Topics</th>
        <th>Last Post</th>
    </tr>
    </thead>
    <tbody>
    {% for board in boards %}
    <tr>
        <td>
            <!--{{ board.name }}-->
            <a href="{% url 'boards:board_topics' board.pk %}">{{ board.name }}</a>
            <small class="text-muted d-block">{{ board.description }}</small>
        </td>
        <td class="align-middle">{{ board.topics.posts.count }}</td>
        <td class="align-middle">{{ board.topics.count }}</td>
        <td></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

boards/templates/boards/new_topic.html
{% extends 'boards/base.html' %}
{% load widget_tweaks %}

{% block title %}
New Topic
{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'boards:home' %}">Boards</a></li>
<li class="breadcrumb-item"><a href="{% url 'boards:board_topics' board.pk %}">{{ board.name }}</a></li>
<li class="breadcrumb-item active">New topic</li>
{% endblock %}

{% block content %}
<!--<form method="post">-->
<!--{% csrf_token %}-->
<!--<div class="form-group">-->
<!--<label for="id_subject">Subject</label>-->
<!--<input type="text" class="form-control" id="id_subject" name="subject">-->
<!--</div>-->
<!--<div class="form-group">-->
<!--<label for="id_message">Message</label>-->
<!--<textarea class="form-control" id="id_message" name="message" rows="5"></textarea>-->
<!--</div>-->
<!--<button type="submit" class="btn btn-success">Post</button>-->
<!--</form>-->

<!--<form method="post">-->
<!--{% csrf_token %}-->
<!--{{ form.as_p }}-->
<!--<button type="submit" class="btn btn-success">Post</button>-->
<!--</form>-->

<!--<form method="post" novalidate>-->
    <!--{% csrf_token %}-->

    <!--{% for field in form %}-->
    <!--<div class="form-group">-->
        <!--{{ field.label_tag }}-->

        <!--{% render_field field class="form-control" %}-->

        <!--{% if field.help_text %}-->
        <!--<small class="form-text text-muted">-->
            <!--{{ field.help_text }}-->
        <!--</small>-->
        <!--{% endif %}-->
    <!--</div>-->
    <!--{% endfor %}-->

    <!--<button type="submit" class="btn btn-success">Post</button>-->
<!--</form>-->

<form method="post" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">Post</button>
</form>
{% endblock %}

boards/templates/boards/topics.html
{% extends 'boards/base.html' %}

{% block title %}
Topics Page
{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'boards:home' %}">Boards</a></li>
<li class="breadcrumb-item active">{{ board.name }}</li>
{% endblock %}

{% block content %}
<!--<div class="container">-->
<!--<ol class="breadcrumb my-4">-->
<!--<li class="breadcrumb-item">Boards</li>-->
<!--<li class="breadcrumb-item active">{{ board.name }}</li>-->
<!--</ol>-->
<!--</div>-->
<div class="mb-4">
<a href="{% url 'boards:new_topic' board.id %}" class="btn btn-primary">New topic</a>
</div>

<table class="table">
    <thead class="thead-dark">
    <tr>
        <th>Topic</th>
        <th>Starter</th>
        <th>Replies</th>
        <th>Views</th>
        <th>Last Update</th>
    </tr>
    </thead>
    <tbody>
    {% for topic in board.topics.all %}
    <tr>
        <td>{{ topic.subject }}</td>
        <td>{{ topic.starter.username }}</td>
        <td>0</td>
        <td>0</td>
        <td>{{ topic.created_at }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

boards/templates/includes/form.html
{% load widget_tweaks %}

{% for field in form %}
<div class="form-group">
    {{ field.label_tag }}

    {% if form.is_bound %}
    {% if field.errors %}
    {% render_field field class="form-control is-invalid" %}
    {% for error in field.errors %}
    <div class="invalid-feedback">
        {{ error }}
    </div>
    {% endfor %}
    {% else %}
    {% render_field field class="form-control is-valid" %}
    {% endif %}
    {% else %}
    {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
    <small class="form-text text-muted">
        {{ field.help_text }}
    </small>
    {% endif %}
</div>
{% endfor %}